import type { Logger } from '../../logger/index.js'
import type { ContentCaptureMode } from '../../harness/defineHarness.js'
import type { HarnessIdentity } from '../../identity/index.js'
import type { JsonValue } from '../../models/json.js'
import type { Metrics, TelemetryShim } from '../../telemetry/index.js'
import type { HarnessContextConfigurable } from '../harness-context.js'
import type { EmbeddingResponse } from '../model-provider.js'

/** Operations a memory engine may advertise. */
export type MemoryCapability =
  | 'memory.kv'
  | 'memory.list'
  | 'memory.delete'
  | 'memory.ttl'
  | 'memory.text_search'
  | 'memory.vector_search'
  | 'memory.hybrid_search'
  | 'memory.persistent'
  | 'memory.multi_instance'

/** Lifetime of information, independent from the optional tenant/principal identity. */
export type MemoryScopeKind = 'application' | 'tenant' | 'principal' | 'session' | 'run' | 'agent'

/** A fully bound namespace passed to an engine. `scopeKey` is generated by core. */
export interface MemoryScope {
  readonly kind: MemoryScopeKind
  readonly scopeKey: string
  readonly sessionId?: string
  readonly runId?: string
  readonly agentId?: string
  readonly identity?: HarnessIdentity
}

/** Immutable canonical record persisted by every memory engine. */
export interface MemoryRecord {
  readonly scopeKey: string
  readonly key: string
  readonly value: JsonValue
  readonly createdAt: string
  readonly updatedAt: string
  readonly expiresAt?: string
  readonly tags?: readonly string[]
  readonly metadata?: Readonly<Record<string, JsonValue>>
  readonly indexText?: string
  readonly vector?: readonly number[]
  readonly indexDescriptor?: MemoryIndexDescriptor
}

/** Prevents incompatible vector embeddings from silently sharing one index. */
export interface MemoryIndexDescriptor {
  readonly alias: string
  readonly providerId: string
  readonly model: string
  readonly dimensions: number
  readonly distance: 'cosine'
  readonly extractorRevision: string
}

export interface MemoryEngineInfo {
  readonly id: string
  readonly packageName: string
  readonly version?: string
}

export interface MemoryEngineContext {
  readonly logger: Logger
  readonly telemetry: TelemetryShim
  readonly metrics: Metrics
  readonly contentCaptureMode: ContentCaptureMode
  readonly signal: AbortSignal
}

/** Names used by core memory spans and operation metrics. */
export type MemoryOperation = 'get' | 'set' | 'delete' | 'list' | 'search'

export interface MemoryListOptions {
  readonly prefix?: string
  readonly limit?: number
  readonly cursor?: string
}

export interface MemoryListResult {
  readonly records: readonly MemoryRecord[]
  readonly cursor?: string
}

export type MemorySearchMode = 'text' | 'semantic' | 'hybrid'

export interface MemorySearchQuery {
  readonly text: string
  readonly mode?: MemorySearchMode
  readonly limit?: number
  readonly cursor?: string
  readonly tags?: readonly string[]
  readonly metadata?: Readonly<Record<string, JsonValue>>
  readonly createdAfter?: string
  readonly createdBefore?: string
  readonly updatedAfter?: string
  readonly updatedBefore?: string
}

export interface MemoryEngineSearchQuery extends MemorySearchQuery {
  readonly vector?: readonly number[]
}

export interface MemorySearchResult {
  readonly record: MemoryRecord
  readonly score?: number
}

/** Database boundary. It deliberately has no access to model routing or session storage. */
export interface MemoryEngine<Capabilities extends readonly MemoryCapability[] = readonly MemoryCapability[]> extends Partial<HarnessContextConfigurable> {
  readonly info: MemoryEngineInfo
  /** Keep literals (`as const`) so builder configuration can reject incompatible models. */
  readonly capabilities: Capabilities
  get(scope: MemoryScope, key: string, context: MemoryEngineContext): Promise<MemoryRecord | undefined>
  put(scope: MemoryScope, record: MemoryRecord, context: MemoryEngineContext): Promise<void>
  delete(scope: MemoryScope, key: string, context: MemoryEngineContext): Promise<void>
  list(scope: MemoryScope, options: MemoryListOptions, context: MemoryEngineContext): Promise<MemoryListResult>
  searchText?(scope: MemoryScope, query: MemoryEngineSearchQuery, context: MemoryEngineContext): Promise<readonly MemorySearchResult[]>
  searchVector?(scope: MemoryScope, query: MemoryEngineSearchQuery, context: MemoryEngineContext): Promise<readonly MemorySearchResult[]>
  searchHybrid?(scope: MemoryScope, query: MemoryEngineSearchQuery, context: MemoryEngineContext): Promise<readonly MemorySearchResult[]>
  close?(): Promise<void>
}

export interface MemoryWriteIndex {
  readonly text?: string
}

export interface MemoryWriteOptions {
  readonly ttlMs?: number
  readonly tags?: readonly string[]
  readonly metadata?: Readonly<Record<string, JsonValue>>
  readonly index?: MemoryWriteIndex
}

export interface MemoryEntry {
  readonly key: string
  readonly createdAt: string
  readonly updatedAt: string
  readonly expiresAt?: string
  readonly tags?: readonly string[]
  readonly metadata?: Readonly<Record<string, JsonValue>>
}

/** Public key/value and recall API bound to one scope. */
export interface SessionMemory {
  read<T = JsonValue>(key: string): Promise<T | undefined>
  write(key: string, value: JsonValue, options?: MemoryWriteOptions): Promise<void>
  delete(key: string): Promise<void>
  list(options?: MemoryListOptions): Promise<MemoryListResult>
  search(query: MemorySearchQuery): Promise<readonly MemorySearchResult[]>
}

/** Memory handles available in workflows, agents, tools, and skills. */
export interface MemoryFacade {
  readonly application: SessionMemory
  readonly session: SessionMemory
  readonly run: SessionMemory
  readonly agent?: SessionMemory
  tenant(): SessionMemory
  principal(): SessionMemory
  scope(kind: MemoryScopeKind): SessionMemory
}

/** Core-only context used to bind public handles to a session identity. */
export interface CreateMemoryFacadeOptions extends MemoryEngineContext {
  readonly engine: MemoryEngine
  readonly harnessName: string
  readonly sessionId: string
  readonly identity?: HarnessIdentity
  readonly runId?: string
  readonly agentId?: string
  readonly embedding?: {
    readonly alias: string
    readonly providerId: string
    readonly model: string
    embed(input: string, signal: AbortSignal): Promise<EmbeddingResponse>
  }
}
